modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mods]]
modId = "particlemuffler"
version = "${version}"
displayName = "Particle Muffler"
authors = "LiquidCatMofu"
description = '''
Client-side area particle suppression with block-based and filtered mufflers.
'''
logoFile = "particlemuffler.png"

[[mixins]]
config = "particlemuffler.mixins.json"

[[dependencies.particlemuffler]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.particlemuffler]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.particlemuffler]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
